DO $$
DECLARE
val INT :=15;
  BEGIN
  IF val>=1 AND VAL<10 THEN
  RAISE NOTICE '% : IS BETWEEN 1 AND 10',val;
  ELSIF val>=10 AND VAL<20 THEN
  RAISE NOTICE '% : IS BETWEEN 10 AND 20',val;
  ELSE
  RAISE NOTICE '% : IS GREATER THAN 20',val;
  END IF;
  END;
$$